# Copyright 2012-2016 splinter authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

language: python
os: linux
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  firefox: latest
env:
  - DRIVER='tests/test_flaskclient.py tests/test_browser.py tests/test_element_list.py tests/test_request_handler.py'
  - DRIVER=tests/test_webdriver.py
  - DRIVER=tests/test_webdriver_remote.py
  - DRIVER='-n 4 tests/test_webdriver_firefox.py'
  - DRIVER='-n 4 tests/test_webdriver_chrome.py'
  - DRIVER='tests/test_djangoclient.py tests/test_zopetestbrowser.py'
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - python: 2.7
      env:
        - DJANGO_VERSION=1.7.11 DRIVER=tests/test_djangoclient.py
        - DRIVER=tests/test_zopetestbrowser.py
    - python: 3.6
      env:
        - DJANGO_VERSION=2.0.6 DRIVER=tests/test_djangoclient.py
        - DRIVER=tests/test_zopetestbrowser.py
    - python: 3.7
      env:
        - DJANGO_VERSION=2.0.6 DRIVER=tests/test_djangoclient.py
        - DRIVER=tests/test_zopetestbrowser.py
    - python: 3.8
      env:
        - DJANGO_VERSION=2.0.6 DRIVER=tests/test_djangoclient.py
        - DRIVER=tests/test_zopetestbrowser.py
before_install:
  - export DISPLAY=:99.0
  - travis_retry wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C $HOME/bin
  - ./travis-install.bash
install:
  - export PATH=$HOME:$PATH
script:
  - pip install tox
  - tox -- ${DRIVER}
